### ISSUE TITLE
关于Activity的四种启动模式和常用的Flags  的疑问

### ISSUE THREAD

**Issue by nicochofly** [sweetwong/Android-Interview-QA#28]
您好，标题所指的TAG，

**注意细节**
 第一项
> 被标记为 singleTask 的 Activity 被创建的时候，只会出现在属于自己的 Task 中，并把这整个 Task 压到调用者 Task 的上面。而当用户切换到后台，这个 Activity 存在的 Task又会被放平（不压到之前调用者的 Task 上）

感觉不是singleTask吧？应该是singleInstance吧？

**Comment by sweetwong** [comment]
您好

这种行为是 singleTask 的一个特点。当 A 进程启动 B 进程的一个 Activity，而且这个 Activity 是被标记为 singleTask，那么 B 进程的整个 Task 都会放到 A 进程的 Task 之上，如果此时 B 进程对应的  Activity 栈下面还有 Activity，当你按返回键时，会发现不会直接返回到原来 A 进程对应的 Activity，而是回到 B 进程的前一个 Activity。

这个我有点不好描述，你看一下这个视频应该就明白了
https://www.bilibili.com/video/BV1CA41177Se

**Comment by nicochofly** [comment]
嗯，没考虑到跨进程的情况。
